// <auto-generated />
using System;
using ApiMemeGenerator.Context;
using ApiMemeGenerator.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiMemeGenerator.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20211015153417_AddPasswordUser")]
    partial class AddPasswordUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("ApiMemeGenerator.Models.Imagen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<double>("Peso")
                        .HasColumnType("REAL");

                    b.Property<string>("URL")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UsuarioCreacionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCreacionId");

                    b.ToTable("Imagen");
                });

            modelBuilder.Entity("ApiMemeGenerator.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("ApiMemeGenerator.Models.Imagen", b =>
                {
                    b.HasOne("ApiMemeGenerator.Models.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId");

                    b.Navigation("UsuarioCreacion");
                });

            modelBuilder.Entity<Usuario>().HasData(
                new Usuario { Id = 1, Name = "Guillermo", Password = "Gmacias", TipoUsuario = Enum.Permisos.Admin }
                );
#pragma warning restore 612, 618
        }
    }
}
